### PR TITLE
Adds user creation date in profile-info screen

### PR DESCRIPTION
**Pull request by StCyr**
Fixes https://github.com/mozzius/graysky/issues/112

# Caveats

* My IDE chokes on `profile.createdAt` since this property is not defined in `AppBskyActorDefs.ProfileViewDetailed`. Not important but not nice since the rest of your code is 100% clean. So, you'd probably want to fix it

### CODE REVIEW

**Comment by mozzius** [comment]
Nice, thanks. I'm sure I can figure out how to extend the type, I've done it before in the past (but since removed it)

**Comment by StCyr** [comment]
I've added proper error handling to the actor's audit log creation date's fetch

**Comment by StCyr** [comment]
'Noticed that I should maybe not use `locale.languageTag` as the app is not translated.

Now, we could get: " This user joined Bluesky on giugno 2012" (Italian) instead of "This user joined Bluesky on June 2012"

**Comment by mozzius** [comment]
Tweaked the wording a little but otherwise great work, thanks!

**Pull request merged**
